### ISSUE TITLE
画面上部にマウスオーバーするとDMMのヘッダが表示される

### ISSUE THREAD

**Issue by anonymous102** [Grabacr07/KanColleViewer#172]
いつもお世話になっております。
4.1.5にて以下のような症状を確認しましたので報告します。

・KanColleViewerの画面上部(例えば母港ボタン付近)にマウスオーバーするとDMMのメニューが展開、表示される。

同バージョンを使用している知人に確認したところ同様の現象が発生しました。
また、画像は分かりやすいよう、マウスオーバー後に左クリック押下後の状態となります。
以上、ご確認いただければ幸いです。

![default](https://cloud.githubusercontent.com/assets/15672801/10971886/ee8ddf56-8419-11e5-9edd-878e0f358807.png)
--

環境

KanColleViewer ver4.1.5
Windows7 64bit Professional
flash 19,0,0,226
IE11

**Comment by Butter-Knife** [comment]
#171 
こちらのIssueにあるスタイルシートを適用するといいみたいです。
Issueでは KanColleViewer.exe.config を書き換えるとよいとありますが、
設定→その他→ユーザースタイルシート の該当部分を書き換えて適用ボタン
これでメニューは出てこなくなると思います。

**Comment by veigr** [comment]
DMMのサイトが変更されたのが原因ですね。
回避策としてはButter-Knifeさんの方法で大丈夫だと思いますが、消すのは .area-menu だけで十分でしょう。
```css
body {
    margin:0;
    overflow:hidden
}

#game_frame {
    position:fixed;
    left:50%;
    top:-16px;
    margin-left:-450px;
    z-index:1
}

.area-pickupgame,
.area-menu
{
    display:none!important;
}
```
既定値も修正しておきます。

#dmm-ntgnavi-renew ごと消してしまう方法も考えられますが、KanColleViewer 単独で無理矢理ポイントチャージする際にちょっと不便なので、 .area-menu だけで良いかなと。。
